### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [Maj1122/prj-rev-bwfs-dasmoto#3]
Alternatively, you could use `h2` as your CSS selector to specify the following shared properties among the 3 headings. That way, you could avoid repetition in specifying them for each of your heading elements individually.

```css
h2 {
  color: white;
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
}
```

https://github.com/Maj1122/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/resources/style.css#L9-L12
